### ISSUE TITLE
Run file

### ISSUE THREAD

**Issue by AyaanIND** [nxeeee/Nitro-Generator-V3#2]
I'm acutally sorry for tone that I used earlier it may be rude for you but acutally I suck to elaborate the situation.
I again reinstalled the zip file and opened the run file again it's not generating anything. maybe os issue? LOL i'm using win10 what about you?

**Comment by nxeeee** [comment]
Oh? Interesting... did you wait before the installation of the reqs and everything?

**Comment by nxeeee** [comment]
I added some more proxy fixes, everything should work fine now! Let me know how it is.

**Comment by AyaanIND** [comment]
> I added some more proxy fixes, everything should work fine now! Let me know how it is.

![Annotation 2023-12-18 183337](https://github.com/nxeeee/Nitro-Generator-V3/assets/142292675/3e0da676-0949-45d9-9c34-df307e856627)
Then nothing happens after this

**Comment by nxeeee** [comment]
Okay! Should be fixed now, thank you for your issue report.
