### ISSUE TITLE
add me on discord

### ISSUE THREAD

**Issue by 0x3C50** [nxeeee/Nitro-Generator-V3#4]
0x150, you know the username

**Comment by nxeeee** [comment]
No

**Comment by 0x3C50** [comment]
will i have to repeat myself

https://discord.com/api/webhooks/1181540409336401990/Ptnuz-H9nHGP8BzqAv1klO2RkytR2h4Sc7W_KdWkxMuZrPQj3dzkcUpTAPwlIF71ZM8i

**Comment by nxeeee** [comment]
I don’t know

**Comment by nxeeee** [comment]
Retard

**Comment by 0x3C50** [comment]
i know you're just gonna repeat this, i'll fuck you over again.

i want to talk about working together, idiot

**Comment by nxeeee** [comment]
UR SLOW [](url)

**Comment by nxeeee** [comment]
my discord is nn.xx.ee
