### ISSUE TITLE
cant run file

### ISSUE THREAD

**Issue by voidbozo** [nxeeee/Nitro-Generator-V3#5]
cant run the file

**Comment by nxeeee** [comment]
Hello! May you provide more details regarding your issue?

**Comment by nxeeee** [comment]
Hi there! I’m pretty sure it has something to do with the uninstalled requirements before executing the python code.
I will be fixing that ASAP, maybe by adding an “install.bat” or “requirements.bat” file. Or simply changing it inside the run.bat.

Until then, please execute the following for the installation of each requirement:
`pip install <requirement>`

examples:
`pip install os`
`pip install json`
`pip install random`

**Comment by voidbozo** [comment]
Defaulting to user installation because normal site-packages is not
writeable
ERROR: Could not find a version that satisfies the requirement os (from
versions: none)
ERROR: No matching distribution found for os

C:\Users\Motia>pip install json
Defaulting to user installation because normal site-packages is not
writeable
ERROR: Could not find a version that satisfies the requirement json (from
versions: none)
ERROR: No matching distribution found for json
still no work

**Comment by nxeeee** [comment]
`pip install json`
`pip install json`
Both in the command prompt of the file

**Comment by voidbozo** [comment]
sstill not wrking
