### ISSUE TITLE
It cant run

### ISSUE THREAD

**Issue by axolotl91** [nxeeee/Nitro-Generator-V3#6]
claims Running...
'pip' is not recognized as an internal or external command,
operable program or batch file.
'pip' is not recognized as an internal or external command,
operable program or batch file.
'pip' is not recognized as an internal or external command,
operable program or batch file.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Press any key to continue . . .

**Comment by unrealisticfaces** [comment]
perhaps you should watch youtube how to run it haha
