### ISSUE TITLE
looping only i guess.

### ISSUE THREAD

**Issue by unrealisticfaces** [nxeeee/Nitro-Generator-V3#7]
i couldn't find any verified value keys on this. it keeps on retrying / looping smth

**Comment by nxeeee** [comment]
Huh?

**Comment by unrealisticfaces** [comment]
it doesn't generate key. it keeps on looping "retry"

**Comment by nxeeee** [comment]
weird

**Comment by unrealisticfaces** [comment]
yeah i run it 4-5hr and it keeps saying "retry" perhaps you should show us a photo that it is currently working.

**Comment by nxeeee** [comment]
Perhaps show me your error screenshot
